# Generated by Django 2.0.5 on 2018-05-18 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180518_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='host_groups',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_begin_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 18, 5, 2, 55, 674504, tzinfo=utc), help_text='yyyy-mm-dd HH:MM:SS'),
        ),
    ]
