# Generated by Django 2.0.5 on 2018-05-18 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180518_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bind_hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.BindHosts', verbose_name='授权主机'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Department', verbose_name='部门'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_groups',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='web.HostGroups', verbose_name='主机组'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='valid_begin_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='yyyy-mm-dd HH:MM:SS'),
        ),
    ]
