# Generated by Django 2.0.5 on 2018-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180518_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bind_hosts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bind_hosts',
            field=models.ManyToManyField(blank=True, null=True, to='web.BindHosts', verbose_name='授权主机'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='host_groups',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='web.HostGroups', verbose_name='主机组'),
        ),
    ]
