# Generated by Django 2.0.5 on 2018-05-19 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180518_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
