# Generated by Django 2.0.5 on 2018-05-22 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='web.Department', verbose_name='部门'),
            preserve_default=False,
        ),
    ]
